export const membersData = [
  {
    name: "Devansh Chaudhary",
    quote: "Chairperson of ACM-JUIT",
    insta: "https://www.instagram.com/devansh_102/",
    github: "",
    linkedin: "",
  },
  {
    name: "Aarhan Khan",
    quote: "Vice Chairperson of ACM-JUIT",
    insta: "https://www.instagram.com/aarhan_._/",
    github: "https://github.com/aarhank",
    linkedin: "https://www.linkedin.com/in/aarhan-k-62742b196/",
  },
  {
    name: "Aayush Gupta",
    quote: "Member of ACM JUIT",
    insta: "",
    github: "",
    linkedin: "",
  },
  {
      name: "Aditya Bansal",
      quote: "member of ACM-JUIT",
      insta: "",
      github: "https://github.com/Aditya3403",
      linkedin: "https://www.linkedin.com/in/aditya-bansal-036b36211/",
  },
  {
      name: "Aayush Gupta",
      quote: "Member",
      insta: "",
      github: "https://github.com/aayush3003",
      linkedin: "",
  },
  {
    name: "Dev Pratap Tyagi",
    quote: "Ex-Chairperson of ACM-JUIT",
    insta: "https://www.instagram.com/_devtyagi_/",
    github: "https://github.com/devptyagi",
    linkedin: "https://www.linkedin.com/in/devtyagi/",
  },
  {
    name: "Animesh Singh",
    quote: "I am a developer of this site",
    insta: "https://www.instagram.com/animesh_0764/",
    github: "https://github.com/Animesh0764",
    linkedin: "https://www.linkedin.com/in/animesh-singh-93bb69251/",
  },
  {
    name: "Chaitanya Anchal",
    quote: "Member of ACM-JUIT",
    insta: "",
    github: "https://github.com/Chaitanya3107",
    linkedin: "",
  },
  {
    name: "Abhay Latiyan",
    quote: "I am a contributer of this site",
    insta: "https://www.instagram.com/abhaylatiyan/",
    github: "https://github.com/AbhayLatiyan",
    linkedin: "https://www.linkedin.com/in/abhay-latiyan-a1b796251/",
  },
  {
    name: "SRIJAN SARASWAT",
    quote: "Member of ACM-JUIT",
    insta: "https://www.instagram.com/__.srijan_saraswat.__/",
    github: "https://github.com/SRIJANSARASWAT",
    linkedin: "https://www.linkedin.com/in/srijan-saraswat-a00b63251/", 
  }
];