export const membersData = [
    {
      name: "Aarhan Khan",
      quote: "developer of this site",
      insta: "https://www.instagram.com/aarhan_._/",
      github: "https://github.com/bdab-x",
      linkedin: "https://www.linkedin.com/in/aarhan-k-62742b196/",
    },
	  {
      name: "Ansh Agrawal",
      quote: "member",
      insta: "",
      github: "",
      linkedin: "",
    },
    {
      name: "Pranav Rajput",
      quote: "member",
      insta: "",
      github: "",
      linkedin: "",
    },
    {
      name: "Shubh Saxena",
      quote: "Member",
      insta: "https://www.instagram.com/_shubh.28/",
      github: "https://github.com/shubh-28",
      linkedin: "",
    },
    {

      name: "Deep Shekhar",
      quote: "Member",
      insta: "https://www.instagram.com/finding_myself_429/",
      github: "https://github.com/deep429",
      linkedin: "https://www.linkedin.com/in/deep-shekhar-2087711b9/",
    },
    {
      name: "Aayush Girdhar",
      quote: "member of ACM JUIT",
      insta: "https://www.instagram.com/g.aayush_/",
      github: "https://github.com/AayushG02",
      linkedin: "https://www.linkedin.com/in/aayushgirdhar/",
    },
    {
      name: "Abhinandan Thakur",
      quote: "member",
      insta: "",
      github: "",
      linkedin: "",
    },  
     {
      name: "Divyansh Sehgal",
      quote: "Member",
      insta: "https://www.instagram.com/divyansh_sehgal/",
      github: "https://github.com/Divi03",
      linkedin: "https://www.linkedin.com/in/divyansh-sehgal-095293222/",
    },
    {
      name: "Saumya Bansal",
      quote: "Member of ACM JUIT",
      insta: "",
      github: "https://github.com/saumyabansal17",
      linkedin: "",
    }, 
    {
      name: "Ujjwal Pathak",
      quote: "Member at ACM JUIT",
      insta: "https://www.instagram.com/ujjwalpathaak/",
      github: "https://github.com/UjjwalPathaak",
      linkedin: "https://www.linkedin.com/in/ujjwal-pathak-55272721b/",
    },
  {
      name: "Paras Dhiman",
      quote: "member of ACM JUIT",
      insta: "https://www.instagram.com/i_._anonymous.re/",
      github: "https://github.com/dhimanparas20",
      linkedin: "https://www.linkedin.com/in/parasdhiman-211382/",
    },
    {
      name: "Aaditya jain",
      quote: "Member of ACM JUIT",
      insta: "https://www.instagram.com/asmodeus__16/",
      github: "https://github.com/Aaditya016",
      linkedin: "https://www.linkedin.com/in/Ajxfifa19/",

    },
     {
      name: "Alisha Siddiqui",
      quote: "Member of ACM JUIT",
      insta: "https://www.instagram.com/aswritessss/",
      github: "https://github.com/aswritesssss",
      linkedin: "https://alishasiddiqui.substack.com/",

    },
    {
      name: "Shivansh Mehrotra",
      quote: "Member of ACM JUIT",
      insta: "https://www.instagram.com/shivanshmehrotra_14",
      github: "https://github.com/S-Mcode2hack",
      linkedin: "https://www.linkedin.com/in/Shivansh-Mehrotra14",
    },
  ];
